name: CI

on:
  # allow manual running
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: 20

    - run: npm ci
    - run: npm run lint

  ember-cli-update:
    needs: lint
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GitHubToken }}
    - uses: actions/setup-node@v5
      with:
        node-version: 20

    - uses: kellyselden/ember-cli-update-action@v7
      with:
        autofix_command: npm run lint -- --fix
        ignore_to: true
